import { CommercialProperty, DynamicIndicators, PropertyType } from "@/types/indicators";

const baseIndicators: DynamicIndicators = {
  faceRent: 0,
  netEffectiveRent: null,
  capRate: undefined,
  priceToRentRatio: undefined,
  wale: undefined,
  retentionRate: undefined,
  tenantConcentration: undefined,
  netAbsorption: undefined,
  reversionRate: undefined,
  spaceUtilization: undefined,
  salesEfficiency: undefined,
  rentToSalesRatio: undefined,
  footfallTicketSize: undefined,
  esgCertification: undefined,
  landFloorPrice: undefined,
  capexIntensity: undefined,
  npiMargin: undefined,
  collectionRate: undefined,
  compTxPrice: undefined,
  noiCagr3Y: undefined,
  submarketVacancy: undefined,
  policyIncentiveLevel: undefined,
  yieldSpread: undefined,
  kolBuzzIndex: undefined,
  negativeSentimentRate: undefined,
  employeeHappinessScore: undefined,
  electricityOutputRatio: undefined,
  taxCovenantRate: undefined,
  loadingDockRatio: undefined,
  anchorDependency: undefined,
  merchantChurnRate: undefined,
  netCorporateMigration: undefined,
  hqSupplyChainRatio: undefined,
  corporateInquiryIndex: undefined,
  firstStoreRatio: undefined,
  openToCloseRatio: undefined,
  culturalRadianceLevel: undefined,
  footfallPulseRate: undefined,
  culturalPremiumScore: undefined,
  pmOperatorTier: undefined,
  facilitySlaRating: undefined,
  maintenanceScore: undefined,
  ltvRatio: undefined,
  debtYield: undefined,
  cashOnCashReturn: undefined,
  projectedIrr5Y: undefined,
  tradeAreaPopulation: undefined,
  demographicPremiumScore: undefined,
};

export const mockProperties: CommercialProperty[] = [
  // --- OFFICE ---
  {
    id: "prop-001",
    projectName: "上海中心大厦",
    city: "上海",
    district: "浦东新区",
    rawAddress: "上海市浦东新区陆家嘴银城中路501号",
    propertyType: PropertyType.OFFICE,
    faceRent: 18.5,
    dataSource: "贝壳商办 · 2026-05-28",
    dynamicIndicators: {
      ...baseIndicators,
      faceRent: 18.5,
      netEffectiveRent: 15.2,
      capRate: 4.8,
      priceToRentRatio: 42,
      wale: 5.2,
      retentionRate: 88,
      tenantConcentration: 35,
      netAbsorption: 12000,
      reversionRate: 5.5,
      spaceUtilization: 82,
      esgCertification: "LEED Platinum + WELL Gold",
      landFloorPrice: 45000,
      capexIntensity: 12000,
      npiMargin: 68,
      collectionRate: 96,
      compTxPrice: 92000,
      noiCagr3Y: 4.2,
      submarketVacancy: 12.5,
      policyIncentiveLevel: 3,
      yieldSpread: 2.1,
      kolBuzzIndex: 78,
      negativeSentimentRate: 3.2,
      employeeHappinessScore: 82,
      netCorporateMigration: 15,
      hqSupplyChainRatio: 45,
      corporateInquiryIndex: 92,
      pmOperatorTier: 5,
      facilitySlaRating: 94,
      maintenanceScore: 88,
      ltvRatio: 55,
      debtYield: 8.5,
      cashOnCashReturn: 7.2,
      projectedIrr5Y: 12.5,
    },
    isUnlocked: false,
    updatedAt: "2026-05-28T10:30:00Z",
  },
  {
    id: "prop-002",
    projectName: "北京国贸三期",
    city: "北京",
    district: "朝阳区",
    rawAddress: "北京市朝阳区建国门外大街1号",
    propertyType: PropertyType.OFFICE,
    faceRent: 22.0,
    dataSource: "点点租 · 2026-05-30",
    dynamicIndicators: {
      ...baseIndicators,
      faceRent: 22.0,
      netEffectiveRent: 18.0,
      capRate: 4.2,
      priceToRentRatio: 52,
      wale: 6.5,
      retentionRate: 92,
      tenantConcentration: 28,
      netAbsorption: 8500,
      reversionRate: 4.8,
      spaceUtilization: 88,
      esgCertification: "LEED Gold",
      landFloorPrice: 68000,
      capexIntensity: 15000,
      npiMargin: 72,
      collectionRate: 98,
      compTxPrice: 105000,
      noiCagr3Y: 3.8,
      submarketVacancy: 8.5,
      policyIncentiveLevel: 4,
      yieldSpread: 1.8,
      kolBuzzIndex: 85,
      negativeSentimentRate: 1.8,
      employeeHappinessScore: 88,
      netCorporateMigration: 22,
      hqSupplyChainRatio: 58,
      corporateInquiryIndex: 95,
      pmOperatorTier: 5,
      facilitySlaRating: 96,
      maintenanceScore: 92,
      ltvRatio: 48,
      debtYield: 9.2,
      cashOnCashReturn: 8.0,
      projectedIrr5Y: 14.0,
    },
    isUnlocked: true,
    updatedAt: "2026-05-30T08:15:00Z",
  },
  // --- SHOPS ---
  {
    id: "prop-003",
    projectName: "深圳万象天地",
    city: "深圳",
    district: "南山区",
    rawAddress: "深圳市南山区深南大道9668号",
    propertyType: PropertyType.SHOPS,
    faceRent: 35.0,
    dataSource: "贝壳商办 · 2026-05-29",
    dynamicIndicators: {
      ...baseIndicators,
      faceRent: 35.0,
      netEffectiveRent: 28.5,
      capRate: 5.5,
      priceToRentRatio: 38,
      wale: 3.5,
      retentionRate: 78,
      tenantConcentration: 45,
      salesEfficiency: 12000,
      rentToSalesRatio: 18.5,
      footfallTicketSize: "885元/客单",
      esgCertification: "二星级绿色建筑",
      landFloorPrice: 28000,
      capexIntensity: 8000,
      npiMargin: 58,
      collectionRate: 94,
      compTxPrice: 75000,
      noiCagr3Y: 6.5,
      submarketVacancy: 5.2,
      policyIncentiveLevel: 5,
      yieldSpread: 3.2,
      kolBuzzIndex: 92,
      negativeSentimentRate: 2.5,
      employeeHappinessScore: 78,
      anchorDependency: 35,
      merchantChurnRate: 8.5,
      firstStoreRatio: 22,
      openToCloseRatio: 2.8,
      culturalRadianceLevel: 4,
      footfallPulseRate: 1.8,
      culturalPremiumScore: 85,
      pmOperatorTier: 4,
      facilitySlaRating: 88,
      maintenanceScore: 85,
      ltvRatio: 52,
      debtYield: 7.8,
      cashOnCashReturn: 6.5,
      projectedIrr5Y: 15.2,
      tradeAreaPopulation: 2800000,
      demographicPremiumScore: 90,
    },
    isUnlocked: false,
    updatedAt: "2026-05-29T14:20:00Z",
  },
  // --- INDUSTRIAL ---
  {
    id: "prop-004",
    projectName: "苏州生物医药产业园",
    city: "苏州",
    district: "工业园区",
    rawAddress: "苏州市工业园区星湖街218号",
    propertyType: PropertyType.INDUSTRIAL,
    faceRent: 2.8,
    dataSource: "好租 · 2026-05-27",
    dynamicIndicators: {
      ...baseIndicators,
      faceRent: 2.8,
      netEffectiveRent: 2.3,
      capRate: 7.2,
      priceToRentRatio: 28,
      wale: 8.0,
      retentionRate: 92,
      tenantConcentration: 55,
      esgCertification: "省级绿色园区",
      landFloorPrice: 3500,
      capexIntensity: 5000,
      npiMargin: 62,
      collectionRate: 97,
      compTxPrice: 18000,
      noiCagr3Y: 8.5,
      submarketVacancy: 6.8,
      policyIncentiveLevel: 5,
      yieldSpread: 4.5,
      kolBuzzIndex: 65,
      negativeSentimentRate: 1.2,
      employeeHappinessScore: 85,
      electricityOutputRatio: 92,
      taxCovenantRate: 105,
      loadingDockRatio: 1.5,
      netCorporateMigration: 32,
      hqSupplyChainRatio: 68,
      corporateInquiryIndex: 88,
      pmOperatorTier: 3,
      facilitySlaRating: 90,
      maintenanceScore: 87,
      ltvRatio: 40,
      debtYield: 10.5,
      cashOnCashReturn: 9.2,
      projectedIrr5Y: 18.5,
    },
    isUnlocked: false,
    updatedAt: "2026-05-27T16:45:00Z",
  },
  // --- SHOPS (unlocked) ---
  {
    id: "prop-005",
    projectName: "成都太古里",
    city: "成都",
    district: "锦江区",
    rawAddress: "成都市锦江区中纱帽街8号",
    propertyType: PropertyType.SHOPS,
    faceRent: 28.0,
    dataSource: "贝壳商办 · 2026-06-01",
    dynamicIndicators: {
      ...baseIndicators,
      faceRent: 28.0,
      netEffectiveRent: 22.0,
      capRate: 5.8,
      priceToRentRatio: 35,
      wale: 4.0,
      retentionRate: 85,
      tenantConcentration: 38,
      salesEfficiency: 15000,
      rentToSalesRatio: 15.0,
      footfallTicketSize: "1280元/客单",
      esgCertification: "LEED Gold + 国家级绿色商圈",
      landFloorPrice: 42000,
      capexIntensity: 10000,
      npiMargin: 65,
      collectionRate: 95,
      compTxPrice: 85000,
      noiCagr3Y: 7.2,
      submarketVacancy: 3.5,
      policyIncentiveLevel: 4,
      yieldSpread: 3.8,
      kolBuzzIndex: 95,
      negativeSentimentRate: 1.5,
      employeeHappinessScore: 82,
      anchorDependency: 28,
      merchantChurnRate: 5.2,
      firstStoreRatio: 32,
      openToCloseRatio: 4.5,
      culturalRadianceLevel: 5,
      footfallPulseRate: 2.5,
      culturalPremiumScore: 95,
      pmOperatorTier: 5,
      facilitySlaRating: 92,
      maintenanceScore: 90,
      ltvRatio: 45,
      debtYield: 8.2,
      cashOnCashReturn: 7.8,
      projectedIrr5Y: 16.0,
      tradeAreaPopulation: 3500000,
      demographicPremiumScore: 92,
    },
    isUnlocked: true,
    updatedAt: "2026-06-01T09:00:00Z",
  },
];

export const cityList = ["上海", "北京", "深圳", "苏州", "成都"];

export const propertyTypeLabels: Record<PropertyType, string> = {
  [PropertyType.OFFICE]: "写字楼",
  [PropertyType.SHOPS]: "商业零售",
  [PropertyType.INDUSTRIAL]: "产业园",
};

export const propertyTypeIcons: Record<PropertyType, string> = {
  [PropertyType.OFFICE]: "🏢",
  [PropertyType.SHOPS]: "🛍️",
  [PropertyType.INDUSTRIAL]: "🏭",
};
